#spring.application.name=shop_49
#spring.datasource.url=jdbc:postgresql://localhost:5432/g_49_shop
#spring.datasource.username=my_user
#spring.datasource.password=pos1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_g49
    username: my_user
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  application:
    name: Shop

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com #Адрес сервера для отправки почти
    port: 587 #Порт для отправки посты через SMTP
    properties:
      mail:
        smtp:
          auth: true #Включаю аутентификацию для SMTP
          starttls:
            enable: true #Включаю шифрование соединения (поддержка TLS)
          ssl:
            protocols: TLSv1.2 #Указываем протокол защиты TLS версии 1.2
            trust: smtp.gmail.com # Добавляем smtp сервер Google в доверенные
          debug: true # Включаю логирование процесса отправки почты

#  freemarker:
#    template-loader-path: classpath:/mail/
#    suffix: .ftlh



server:
  servlet:
    context-path: /api
#  error:
#    include-message: always
#    include-binding-errors: always

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

logging:
  file:
    name: logs/log.log
  level:
    root: info